name: Python CI CD

on:  push


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    steps:
    - name: Set up Pytest
      uses: actions/setup-pytest@v2
      with:
        /*- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies*/
        py.test -h
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        python test_calculator.py

